### ISSUE TITLE
Days skipped when daysCount<7

### ISSUE THREAD

**Issue by AntonioRedondo** [hurkanyakay/react-weekly-day-picker#1]
Hi Hürkan,

Congratulations for this great piece of code! At our company we were looking for some date picker, and only yours covers all our requirements.

We have however found an issue: if the prop `daysCount` is less than 7, let's say 5, the days 6 and 7 will be skipped when the _Next_ or _Prev_ buttons are pressed. It looks like the issue is on line [245](https://github.com/hurkanyakay/react-weekly-day-picker/blob/7700c471908c90c261cb4de61fbab89c15be4937/src/index.js#L245) and line [250](https://github.com/hurkanyakay/react-weekly-day-picker/blob/7700c471908c90c261cb4de61fbab89c15be4937/src/index.js#L250). Instead of 7,  `daysCount` should be the amount to subtract or add.

What do you think?

EDIT: since the issue was easy to fix I've just created a pull request for it: https://github.com/hurkanyakay/react-weekly-day-picker/pull/2.

EDIT 2: we have devised another issue. Would it be possible to include two extra props accepting a function that would be called every time the _Prev_ or _Next_ buttons are pressed? This is needed in order to keep track of which date slot the user is after moving back or forward. If not specified `startDate` will always resort to today on every re-render. So if the user selects a day which is not on the initial date frame, the frame will return to the initial one because there will be new props (`selectedDays`) firing re-rendering. If however there were these two props, let's called them `onPrevClick` and `onNextClick`, we could keep track of the current date frame and updating `startDate` accordingly.

EDIT 3: actually there was a bug related with EDIT 2. Line [108](https://github.com/hurkanyakay/react-weekly-day-picker/blob/master/src/index.js#L108) should be `convertedStartDay = this.state.startDay;` rather than `convertedStartDay = moment();`. I've updated https://github.com/hurkanyakay/react-weekly-day-picker/pull/2 to fix the bug. For convenience I've also included the new props `onPrevClick` and `onNextClick` and updated documentation. :)

**Comment by hurkanyakay** [comment]
@AntonioRedondo thanks for the contribution. I am open to any kind of additions and modifications.I will merge your PR ASAP.

**Comment by hurkanyakay** [comment]
I just published new version 1.0.1 if you are using npm version @AntonioRedondo

**Comment by AntonioRedondo** [comment]
Lovely! Thank you very much!
